name: Python lint and test

on: [push]

env:
    PYTHON_VERSION: "3.10.13"
    POETRY_VERSION: "1.6.1"
    POETRY_URL: https://install.python-poetry.org

jobs:
    lint-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ env.PYTHON_VERSION }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ env.PYTHON_VERSION }}
            - name: Install Poetry ${{ env.POETRY_VERSION }}
              run: |
                  curl -sSL ${{ env.POETRY_URL }} | python - --version ${{ env.POETRY_VERSION }}
                  echo "$HOME/.local/bin" >> $GITHUB_PATH
            - name: Install Dependencies
              run: poetry install
            - name: Lint
              run: make lint
            - name: Test
              run: make test
